# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [71]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [72]:
print(np.__version__)
np.show_config()

1.23.1
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [73]:
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [74]:
z=np.zeros((10,10))
print("%d bytes" % (z.size * z.itemsize))

800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [75]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [76]:
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [77]:
z=np.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [78]:
z=np.arange(50)
z=z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [79]:
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [80]:
z=np.nonzero([1,2,0,0,4,0])
print(z)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [81]:
z=np.eye(3,3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [82]:
z=np.random.random((3,3,3))
print(z)

[[[0.13154101 0.1233283  0.47599159]
  [0.55349162 0.3934571  0.6055166 ]
  [0.36446072 0.79981543 0.18270055]]

 [[0.701029   0.99303305 0.9679388 ]
  [0.22774183 0.78529482 0.89915894]
  [0.20525869 0.61045942 0.61449565]]

 [[0.51992935 0.26536519 0.92315995]
  [0.48846615 0.32098279 0.49843162]
  [0.39935362 0.887159   0.79315597]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [83]:
z=np.random.random((10,10))
zmin, zmax = z.min(), z.max()
print(zmin, zmax)

0.014128898862996175 0.9947022346298142


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [84]:
z=np.random.random(30)
m=z.min()
print(m)

0.04342328959816455


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [85]:
z=np.ones((10,10))
z[1:-1, 1:-1]=0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [86]:
z = np.ones((5,5))
z = np.pad(z, pad_width=1, mode='constant', constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [87]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf>np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [88]:
z=np.diag(1+np.arange(4), k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [89]:
z=np.zeros((8,8), dtype=int)
z[1::2,::2]=1
z[::2,1::2]=1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [90]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [91]:
z=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [92]:
z=np.random.random((5,5))
z=(z-np.mean(z))/(np.std(z))
print(z)

[[-0.49198275 -1.13979368  0.19805592 -1.52453301 -0.77351156]
 [ 1.31194702  1.03387558  0.08148371  0.20858928  1.40477831]
 [-1.44842078  1.41829138 -0.956838   -0.68486001 -1.41541091]
 [ 1.36205633  0.28839796 -1.03892938  0.64977954 -0.98751351]
 [ 0.38894244  1.16161951  0.05872429  1.41355146 -0.51829914]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [93]:
color = np.dtype([('r',np.ubyte, 1),
                 ('g', np.ubyte, 1),
                 ('b',np.ubyte,1),
                 ('a', np.ubyte,1)])

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_8208\3657547592.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([('r',np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [94]:
z=np.dot(np.ones((5,3)), np.ones((3,2)))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [105]:
z = np.ones((5,3)) @ np.ones((3,2))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [106]:
z=np.arange(11)
z[(2 < z) & (z<=8)] *= -1
print(z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [107]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [191]:
#Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z

array([[1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 1.],
       [0., 1., 1.],
       [1., 0., 1.],
       [1., 0., 0.]])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [110]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\ELCOT\AppData\Local\Temp\ipykernel_8208\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\ELCOT\AppData\Local\Temp\ipykernel_8208\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [111]:
z=np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(z)),z))

[ 7. -8. -3. -6. -4. -7. -3.  5. -7. -7.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [112]:
z1=np.random.randint(0,10,10)
z2=np.random.randint(0,10,10)
print(np.intersect1d(z1,z2))

[0 3 5 7 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [113]:
defaults = np.seterr(all='ignore')
z=np.ones(1)/0

_ = np.seterr(**defaults)

with np.errstate(divide = 'ignore'):
    z=np.ones(1)/0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [114]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


C:\Users\ELCOT\AppData\Local\Temp\ipykernel_8208\2770867030.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [115]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2022-08-18 2022-08-19 2022-08-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [116]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [117]:
a=np.ones(3)*1
b=np.ones(3)*2
c=np.ones(3)*3
np.add(a,b,out=b)
np.negative(a, out=a)
np.multiply(a,b, out=a)
np.divide(a,2,out=a)


array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [118]:
z=np.random.uniform(0,10,10)
print(z-z%1)
print(np.floor(z))
print(np.ceil(z)-1)
print(z.astype(int))
print(np.trunc(z))

[2. 9. 8. 2. 7. 8. 1. 4. 5. 6.]
[2. 9. 8. 2. 7. 8. 1. 4. 5. 6.]
[2. 9. 8. 2. 7. 8. 1. 4. 5. 6.]
[2 9 8 2 7 8 1 4 5 6]
[2. 9. 8. 2. 7. 8. 1. 4. 5. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [119]:
z=np.zeros((5,5))
z +=np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [120]:
def generator():
    for x in range(10):
        yield x
z=np.fromiter(generator(), dtype=float, count=-1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [121]:
print(np.linspace(0,1,11, endpoint=False)[1:])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [122]:
z=np.random.random(10)
z.sort()
print(z)

[0.14259421 0.21133418 0.22923743 0.25633193 0.3029542  0.42220466
 0.57528049 0.59444636 0.63261953 0.77972168]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [123]:
z=np.arange(10)
np.add.reduce(z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [124]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal=np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [125]:
z=np.zeros(10)
z.flags.writeable=False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [126]:
z=np.random.random((10,2))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2 + y**2)
t = np.arctan2(y, x)
print(r)
print(t)

[0.85609385 0.74762636 1.24086487 0.91743466 0.4356332  0.81642592
 0.41364536 0.83226334 0.92958586 0.9533105 ]
[1.18378918 0.09128522 0.72489511 0.10327447 1.35006896 0.33964033
 0.82910615 0.77829439 0.0436491  1.52707351]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [127]:
z=np.random.random(10)
z[z.argmax()]=0
print(z)

[0.         0.57939158 0.31398458 0.07117808 0.80240578 0.64011193
 0.64323202 0.72289568 0.63390931 0.14658889]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [128]:
z=np.zeros((5,5), [('x',float), ('y',float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [129]:
x = np.arange(8)
y = x + 0.5
c = 1.0 + np.subtract.outer(x,y)
print(np.linalg.det(c))

1.6107962933007784e-91


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [130]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [131]:
np.set_printoptions(threshold=None)
z=np.zeros((16,16))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [132]:
z=np.arange(100)
v=np.random.uniform(0,100)
index = (np.abs(z-v)).argmin()
print(z[index])

48


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [133]:
z=np.zeros(10, [('position', [('x', float, 1),
                             ('y', float, 1)]),
               ('colors', [('r', float, 1),
                          ('g', float, 1),
                          ('b', float, 1)])])
print(z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\ELCOT\AppData\Local\Temp\ipykernel_8208\1293986043.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  z=np.zeros(10, [('position', [('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [134]:
z=np.random.random((10,2))
x,y=np.atleast_2d(z[:,0], z[:,1])
d=np.sqrt((x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.27676066 0.50131589 0.44087542 0.30405934 0.67828525
  0.30714354 0.76675284 0.29240083 0.51230735]
 [0.27676066 0.         0.66304204 0.32009584 0.48349058 0.94594896
  0.10018219 0.90440573 0.26156695 0.29209839]
 [0.50131589 0.66304204 0.         0.52524566 0.1974057  0.51328416
  0.74433762 0.26686089 0.43160459 0.6991801 ]
 [0.44087542 0.32009584 0.52524566 0.         0.42306979 0.95844316
  0.41833459 0.70364114 0.15731518 0.17841966]
 [0.30405934 0.48349058 0.1974057  0.42306979 0.         0.53571998
  0.55718211 0.4628479  0.28925388 0.57765251]
 [0.67828525 0.94594896 0.51328416 0.95844316 0.53571998 0.
  0.9853668  0.63111452 0.81703039 1.10573113]
 [0.30714354 0.10018219 0.74433762 0.41833459 0.55718211 0.9853668
  0.         0.99260057 0.35883078 0.36836325]
 [0.76675284 0.90440573 0.26686089 0.70364114 0.4628479  0.63111452
  0.99260057 0.         0.65292831 0.88173098]
 [0.29240083 0.26156695 0.43160459 0.15731518 0.28925388 0.81703039
  0.35883078 0.652928

In [135]:
import scipy
import scipy.spatial

z = np.random.random((10,2))
d = scipy.spatial.distance.cdist(z,z)
print(d)

[[0.         0.61445721 0.60571386 0.52007463 0.37445616 0.80845363
  0.56128373 0.51271367 0.31566261 0.59339394]
 [0.61445721 0.         0.08254619 0.43274879 0.9882567  0.21581053
  0.4571581  0.54744851 0.89850345 0.83121037]
 [0.60571386 0.08254619 0.         0.35869024 0.9750836  0.20273996
  0.3800471  0.47621922 0.90330461 0.7647072 ]
 [0.52007463 0.43274879 0.35869024 0.         0.81880089 0.49527084
  0.04393291 0.12066877 0.83129954 0.41449532]
 [0.37445616 0.9882567  0.9750836  0.81880089 0.         1.17730694
  0.85243083 0.76544599 0.22040291 0.6946783 ]
 [0.80845363 0.21581053 0.20273996 0.49527084 1.17730694 0.
  0.50145736 0.61551717 1.10432885 0.90935801]
 [0.56128373 0.4571581  0.3800471  0.04393291 0.85243083 0.50145736
  0.         0.12033288 0.87109431 0.40990086]
 [0.51271367 0.54744851 0.47621922 0.12066877 0.76544599 0.61551717
  0.12033288 0.         0.80899935 0.29392024]
 [0.31566261 0.89850345 0.90330461 0.83129954 0.22040291 1.10432885
  0.87109431 0.80899

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [136]:
z=np.arange(10, dtype=np.float32)
z=z.astype(np.int32, copy=False)
print(z)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [137]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9, 10,11\n''')
z=np.genfromtxt(s, delimiter=',', dtype= np.int)
print(z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\ELCOT\AppData\Local\Temp\ipykernel_8208\4147279411.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  z=np.genfromtxt(s, delimiter=',', dtype= np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [138]:
z=np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(z):
    print(index, value)
for index in np.ndindex(z.shape):
    print(index, z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [139]:
x,y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d=np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g=np.exp(-((d-mu)**2/(2.0 * sigma **2)))
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [140]:
n=10
p=3
z=np.zeros((n,n))
np.put(z, np.random.choice(range(n*n), p, replace=False), 1)
print(z)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [141]:
x=np.random.rand(5,10)
y=x-x.mean(axis=1, keepdims=True)
print(y)

[[-0.0265242  -0.17692459  0.42310862 -0.28648517 -0.21054874  0.01411917
   0.33145999  0.13157554  0.14636648 -0.3461471 ]
 [ 0.06610032 -0.10382187  0.19698636  0.04971089  0.03003863  0.31447089
   0.24246124 -0.0874284  -0.35181399 -0.35670406]
 [-0.16200707  0.21962976 -0.21344271 -0.15961387 -0.20391976  0.37414022
  -0.07834577 -0.22541647  0.19148037  0.2574953 ]
 [-0.27968999 -0.24449289 -0.04511864  0.3261863  -0.01498991  0.2596759
   0.2230273  -0.26448357 -0.1341893   0.1740748 ]
 [ 0.45311417 -0.38183768  0.09257599  0.42000977 -0.34942619 -0.03203968
   0.0807948  -0.35273672 -0.36978686  0.4393324 ]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [142]:
z=np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[7 9 9]
 [4 4 5]
 [2 4 9]]
[[4 4 5]
 [2 4 9]
 [7 9 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [143]:
z=np.random.randint(0,3,(3, 10))
print((~z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [144]:
z=np.random.uniform(0,1,10)
x=0.5
m=z.flat[np.abs(z-x).argmin()]
print(m)

0.4874377288085018


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [145]:
a=np.arange(3).reshape(3,1)
b=np.arange(3).reshape(1,3)
iter = np.nditer([a,b,None])
for x, y, z in iter: z[...] = x + y
print(iter.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [146]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [147]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
np.add.at(Z, I, 1)
print(Z)

[3. 4. 2. 2. 3. 4. 5. 1. 4. 2.]


In [148]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[5. 3. 4. 3. 1. 2. 1. 4. 2. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [149]:
x=[1,2,3,4,5,6]
y=[1,3,9,3,4,1]

z=np.bincount(y,x)

print(z)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [150]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [151]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)

[[54 56 58 63]
 [49 58 33 76]
 [48 62 68 43]]


In [152]:
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[54 56 58 63]
 [49 58 33 76]
 [48 62 68 43]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [153]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.46052686 0.45946062 0.57363057 0.52427124 0.4810609  0.50174074
 0.45825286 0.57847698 0.55899304 0.54551915]


In [154]:
import pandas as pd
print(pd.Series(D).groupby(S).mean())

0    0.460527
1    0.459461
2    0.573631
3    0.524271
4    0.481061
5    0.501741
6    0.458253
7    0.578477
8    0.558993
9    0.545519
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [155]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.46667212, 2.07979337, 1.03472537, 0.81374913, 1.11275655])

In [156]:
np.sum(A * B.T, axis=1)

array([1.46667212, 2.07979337, 1.03472537, 0.81374913, 1.11275655])

In [157]:
np.einsum("ij,ji->i", A, B)

array([1.46667212, 2.07979337, 1.03472537, 0.81374913, 1.11275655])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [158]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [159]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [160]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [161]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[(20, 27) (20, 49) (20, 70) (20, 94) (22, 39) (22, 71) (27, 94) (31, 50)
 (31, 95) (33, 60) (33, 93) (39, 71) (41, 63) (41, 69) (45, 49) (45, 76)
 (48, 60) (48, 66) (48, 72) (48, 89) (49, 70) (49, 76) (50, 95) (60, 66)
 (60, 93) (63, 69) (66, 81) (66, 84) (72, 89) (81, 84)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [162]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [163]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [164]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [165]:
z=np.random.randint(0,2,100)
np.logical_not(z, out=z)
z=np.random.uniform(-1.0,1.0,100)
np.negative(z, out=z)

array([-0.0396053 , -0.23251647,  0.98306649, -0.70403917, -0.94360012,
        0.30576956, -0.20881154,  0.97229923,  0.67112057, -0.39721943,
       -0.46551262, -0.4507007 , -0.14247608, -0.48060848,  0.99903201,
       -0.11623263, -0.99098654, -0.5852552 , -0.66954665,  0.87203793,
       -0.59303797, -0.38231301,  0.43837853,  0.34484179, -0.40246675,
        0.84086214, -0.05195798,  0.74356644, -0.5169408 ,  0.75759826,
        0.33388613, -0.66548762,  0.1278369 ,  0.32847045, -0.65249113,
       -0.15209761, -0.92862893,  0.49897852, -0.86550406, -0.73179554,
       -0.78425229,  0.80019729, -0.10461407, -0.04210473,  0.4327672 ,
       -0.75854992, -0.17388977,  0.03301011, -0.38851404, -0.34183481,
       -0.28863215,  0.46249908, -0.24452288, -0.10866912,  0.15331784,
        0.60231531,  0.09167887,  0.08577136,  0.90061193,  0.72684009,
        0.21323448,  0.86526436, -0.38212638, -0.11021887, -0.50068779,
        0.7073311 , -0.82801926, -0.68200997, -0.57208408, -0.87

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [166]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 3.88852277  7.07118809  4.8744087   5.29834836  2.59184218 17.10442151
  4.22610389  5.9181264   3.87705839  4.83984783]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [167]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[17.41838662 12.8183339  13.36888782  2.80790679 12.63476873  4.52614366
   9.47711969  9.95994063  7.35905884 15.26152232]
 [ 7.26676919  2.82205662  3.25024785  2.8572903   2.78469065  4.52316603
   9.62642818  1.43544009  0.41842961  5.14030173]
 [ 1.33372859  6.71743201  6.0194076  11.5062949   6.9174713  14.45409236
   5.29419451  8.43519104  8.89887912  4.12005178]
 [15.80410763 10.61380228 11.35943798  0.30407897 10.28889904  1.7865225
   6.93975135  7.08301491  4.28105459 13.25826101]
 [ 0.51850156  4.67661173  4.40068649  6.59976632  4.5570354  11.10887414
  10.43840679  4.68767248  4.36666221  2.51440878]
 [ 7.12187333  4.06877097  4.01049727  2.05753666  4.40534852  1.71376375
  15.41498829  4.75110143  4.7800468   5.88560514]
 [12.40858265  4.77117242  6.34772988 11.18458705  3.82632141  6.52581729
   3.41819946  1.95090711  6.06376211  8.27250647]
 [ 2.79362129  7.22446013  6.86866551  8.97521332  7.15442913 13.78740346
   9.19104107  7.35898725  6.90952783  4.97966601]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [168]:
Z = np.random.randint(0,10,(10,10))
#print(Z)

shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
#R[r] = Z[z]
print(Z)
print(R)

[[1 0 3 3 5 6 8 3 9 9]
 [6 0 0 2 5 8 2 9 0 0]
 [1 4 1 6 1 8 0 8 9 7]
 [4 8 1 7 3 1 0 4 5 6]
 [3 2 5 5 1 1 0 8 0 9]
 [2 4 4 0 9 7 3 0 9 6]
 [0 5 4 7 8 0 0 7 8 2]
 [3 8 0 5 8 0 1 4 6 4]
 [6 1 8 6 5 1 4 0 7 2]
 [9 2 4 8 0 4 1 8 1 9]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [169]:
z = np.arange(1,15,dtype=np.uint32)
r = np.lib.stride_tricks.as_strided(z,(11,4),(4,4))
print(r)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [170]:
z = np.random.uniform(0,1,(10,10))
u, s, v = np.linalg.svd(z)
rank = np.sum(s > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [171]:
z = np.random.randint(0,10,50)
print(np.bincount(z).argmax())

3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [172]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[4 1 3]
   [4 4 2]
   [3 1 1]]

  [[1 3 0]
   [4 2 4]
   [1 1 1]]

  [[3 0 3]
   [2 4 3]
   [1 1 0]]

  [[0 3 0]
   [4 3 0]
   [1 0 1]]

  [[3 0 1]
   [3 0 2]
   [0 1 1]]

  [[0 1 0]
   [0 2 2]
   [1 1 1]]

  [[1 0 1]
   [2 2 1]
   [1 1 3]]

  [[0 1 0]
   [2 1 0]
   [1 3 4]]]


 [[[4 4 2]
   [3 1 1]
   [0 4 1]]

  [[4 2 4]
   [1 1 1]
   [4 1 0]]

  [[2 4 3]
   [1 1 0]
   [1 0 1]]

  [[4 3 0]
   [1 0 1]
   [0 1 4]]

  [[3 0 2]
   [0 1 1]
   [1 4 4]]

  [[0 2 2]
   [1 1 1]
   [4 4 1]]

  [[2 2 1]
   [1 1 3]
   [4 1 0]]

  [[2 1 0]
   [1 3 4]
   [1 0 0]]]


 [[[3 1 1]
   [0 4 1]
   [0 2 0]]

  [[1 1 1]
   [4 1 0]
   [2 0 2]]

  [[1 1 0]
   [1 0 1]
   [0 2 2]]

  [[1 0 1]
   [0 1 4]
   [2 2 2]]

  [[0 1 1]
   [1 4 4]
   [2 2 0]]

  [[1 1 1]
   [4 4 1]
   [2 0 4]]

  [[1 1 3]
   [4 1 0]
   [0 4 4]]

  [[1 3 4]
   [1 0 0]
   [4 4 4]]]


 [[[0 4 1]
   [0 2 0]
   [4 3 1]]

  [[4 1 0]
   [2 0 2]
   [3 1 0]]

  [[1 0 1]
   [0 2 2]
   [1 0 4]]

  [[0 1 4]
   [2 2 2]
   [0 4 2]]

  [[1 4 4]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [173]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 2 14 11 11  6]
 [14  0 10  7  5]
 [11 10  3 42  2]
 [11  7 42  5 13]
 [ 6  5  2 13  5]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [174]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [175]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [176]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [177]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [178]:
print (Z[np.argpartition(-Z,n)[:n]])

[9999 9998 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [179]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [180]:
Z = np.array([("Hello", 2.5, 3), ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, names='col1, col2, col3', formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [181]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.49 s ± 296 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.03 s ± 19.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
620 ms ± 32 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [183]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 3 4 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [184]:
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 4 1]
 [4 3 3]
 [3 3 0]
 [1 1 3]
 [4 4 4]
 [4 2 4]
 [1 3 2]
 [3 2 2]
 [3 1 4]
 [3 1 1]]
[[4 4 1]
 [4 3 3]
 [3 3 0]
 [1 1 3]
 [4 2 4]
 [1 3 2]
 [3 2 2]
 [3 1 4]
 [3 1 1]]
[[4 4 1]
 [4 3 3]
 [3 3 0]
 [1 1 3]
 [4 2 4]
 [1 3 2]
 [3 2 2]
 [3 1 4]
 [3 1 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [185]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [186]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [187]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A)
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B)
np.einsum('i,j->ij', A, B)

array([[0.84858266, 0.09143572, 0.70480584, 0.66086825, 0.23607419,
        0.26318432, 0.05344672, 0.4909117 , 0.54539521, 0.50951118],
       [0.04408502, 0.00475021, 0.03661562, 0.034333  , 0.01226437,
        0.01367278, 0.00277663, 0.02550353, 0.02833402, 0.0264698 ],
       [0.11628109, 0.01252942, 0.09657938, 0.09055863, 0.03234919,
        0.03606409, 0.00732379, 0.06726952, 0.07473538, 0.0698182 ],
       [0.73868622, 0.07959425, 0.61352935, 0.57528193, 0.20550119,
        0.22910041, 0.04652505, 0.42733575, 0.47476333, 0.44352649],
       [0.39146195, 0.04218046, 0.32513588, 0.30486691, 0.10890402,
        0.12141027, 0.02465565, 0.2264638 , 0.25159773, 0.23504398],
       [0.10480237, 0.01129257, 0.08704552, 0.0816191 , 0.02915583,
        0.03250401, 0.00660082, 0.06062899, 0.06735786, 0.06292608],
       [0.4002638 , 0.04312887, 0.33244642, 0.31172171, 0.11135268,
        0.12414013, 0.02521002, 0.23155574, 0.2572548 , 0.24032884],
       [0.96830862, 0.10433632, 0.8042464

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [188]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [189]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [190]:
X = np.random.randn(100) 
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.26409693  0.12472999]
